!!python/object:argparse.Namespace
baryproj: !!python/object:argparse.Namespace
  logging: !!python/object:argparse.Namespace
    log_path: /home/mounted/LargeScaleOptimalTransport/baryproj/exp
    verbose_stderr: info
compatibility: !!python/object:argparse.Namespace
  logging: !!python/object:argparse.Namespace
    log_path: /home/mounted/LargeScaleOptimalTransport/compatibility/exp
    resume_training: false
    verbose_stderr: info
  model: !!python/object:argparse.Namespace
    architecture: fcn
    hidden_layers:
    - 2048
    - 2048
    - 2048
    - 2048
    - 2048
    - 2048
    - 2048
    - 2048
  optim: !!python/object:argparse.Namespace
    amsgrad: false
    beta1: 0.9
    eps: 1.0e-09
    lr: 1.0e-05
    optimizer: Adam
    weight_decay: 0.0
  training: !!python/object:argparse.Namespace
    batch_size: 64
    n_iters: 101
    num_batches: 20
    seed: 42
    snapshot_freq: 100
device_gpus: !!python/object:argparse.Namespace
  glow_device: cuda:2
  ngpu: 2
  samples_device: cuda:2
logging: !!python/object:argparse.Namespace
  verbose_logger: info
  verbose_stderr: info
meta: !!python/object:argparse.Namespace
  divergence: KL
  problem_name: benchmark_images
  regularization: 100
  task: identity
scones: !!python/object:argparse.Namespace
  logging: !!python/object:argparse.Namespace
    log_path: /home/mounted/LargeScaleOptimalTransport/scones/exp
    verbose_stderr: info
source: !!python/object:argparse.Namespace
  data: !!python/object:argparse.Namespace
    channels: 3
    dataset: benchamrk
    dim: 12288
    gaussian_dequantization: false
    image_size: 64
    logit_transform: false
    num_workers: 0
    random_flip: true
    rescaled: false
    uniform_dequantization: false
target: !!python/object:argparse.Namespace
  data: !!python/object:argparse.Namespace
    channels: 3
    dataset: benchmark
    dim: 12288
    gaussian_dequantization: false
    image_size: 64
    logit_transform: false
    num_workers: 0
    random_flip: true
    rescaled: false
    uniform_dequantization: false
transport: !!python/object:argparse.Namespace
  coeff: 100
  cost: half-l2-sq
  regularization: entropy
